export const LESSONS = [
  {
    step: 0,
    title: "LIDAR Scan Cycle",
    body: "This simulation models a rotating LIDAR sensor mounted on an F1 autonomous vehicle. The cyan sweep represents one scan cycle — a full 360° rotation. Every rotation, the sensor samples its surroundings and builds a point cloud of detected objects.",
    highlight: 'canvas',
    action: null,
    actionLabel: null,
    expectedOutcome: null,
  },
  {
    step: 1,
    title: "The Blind-Distance Equation",
    body: "Between any two scan cycles, moving objects travel an unmonitored distance. The equation d_blind = v/f defines this gap. Watch the equation panel update as you adjust the scan frequency slider. When d_blind exceeds 0.6m — average human shoulder width — a pedestrian can pass through undetected.",
    highlight: 'equation',
    action: null,
    actionLabel: null,
    expectedOutcome: null,
  },
  {
    step: 2,
    title: "Proof: 2 Hz Scan — Pedestrian Missed",
    body: "Frequency is now set to 2 Hz. Scan period = 500ms. A pedestrian at 1.4 m/s travels 0.70m between sweeps — wider than shoulder width. But watch what happens at the crosswalk. Press WALK to run the test.",
    highlight: 'canvas',
    action: 'setFrequency2',
    actionLabel: 'WALK ↗',
    expectedOutcome: 'missDetect',
  },
  {
    step: 3,
    title: "Proof: 20 Hz Scan — Pedestrian Caught",
    body: "Frequency is now 20 Hz. Scan period = 50ms. The pedestrian travels only 0.07m between sweeps — well within the 0.6m body width. The sensor will catch them on the next sweep. Press WALK to verify.",
    highlight: 'canvas',
    action: 'setFrequency20',
    actionLabel: 'WALK ↗',
    expectedOutcome: 'hitDetect',
  },
  {
    step: 4,
    title: "Your Data Is Live",
    body: "Every value in the telemetry panel is a real observation for your Jain University report. The missed detection count is your Results table. The d_blind calculation is your Calculations section. The weather confidence drop demonstrates the Beer-Lambert scattering law from your Theory section.",
    highlight: 'telemetry',
    action: null,
    actionLabel: null,
    expectedOutcome: null,
  },
];
